name: flutter_billing_example
description: Demonstrates how to use the flutter_billing plugin.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_billing:
    path: ../

flutter:
  uses-material-design: true
