name: flutter_billing
description: A flutter plugin to communicate with billing on iOS and Android.
version: 0.1.2
author: Volodymyr Lykhonis <vladimirlichonos@gmail.com>
homepage: http://vladimirlichonos.com

dependencies:
  flutter:
    sdk: flutter
  synchronized: ^1.1.0

flutter:
  plugin:
    androidPackage: com.lykhonis.flutterbilling
    pluginClass: BillingPlugin

environment:
  sdk: ">=1.8.0 <2.0.0"
