name: flutter_billing
description: A flutter plugin to communicate with billing on iOS and Android.
version: 0.0.1
author: Volodymyr Lykhonis <vladimirlichonos@gmail.com>
homepage: http://vladimirlichonos.com

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.lykhonis.flutterbilling
    pluginClass: BillingPlugin
